version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    environment:
      JVM_OPTS: -Xmx1g
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "versions.lock" }}

      - run:
          name: Compile
          command: ./gradlew --build-cache testClasses
          environment:
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=3 -Xmx768m

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v2-dependencies-{{ checksum "versions.lock" }}-{{ epoch }}

      - run:
          name: Test
          command: ./gradlew --build-cache test
          environment:
            GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=3 -Xmx768m

      - store_test_results:
          name: Store test results
          path: build/test-results

      - store_artifacts:
          name: Store gradle reports
          path: build/reports
