version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "versions.lock" }}

      - run: ./gradlew testCompile

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "versions.lock" }}

      - run: ./gradlew test
